version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Gatsby
          command: sudo npm install -g gatsby-cli
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      # - run:
      #     name: Install Python dependencies
      #     command: sudo apt install python-pip python-dev
      - run:
          name: Install AWS CLI
          command: sudo apt-get install -y awscli --upgrade --user
      - run:
          name: Deploy to S3
          command: aws --version